services:
  postgres:
    image: postgres:14
    container_name: insurance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: insurance
      POSTGRES_PASSWORD: insurance
      POSTGRES_DB: insurance_db
    ports:
      - "5433:5432"   # mapeia host:container -> usa 5433 no host para evitar conflito com postgres local
    volumes:
      - pgdata_insurance:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_insurance:
