-- schema.sql
-- Cria a tabela policies (compatível H2 / Postgres)
CREATE TABLE IF NOT EXISTS policies (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  numero_apolice VARCHAR(50) NOT NULL,
  cpf_segurado VARCHAR(20) NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  placa_veiculo VARCHAR(20),
  valor_premio NUMERIC(15,2),
  CONSTRAINT uk_policy_numero UNIQUE (numero_apolice)
);

-- índice adicional (opcional) para busca por número
CREATE INDEX IF NOT EXISTS idx_policies_numero ON policies (numero_apolice);
